export enum OnboardingStep {
  USER_INFO = "USER_INFO",
  PICK_HOUSEHOLD_OPTION = "PICK_HOUSEHOLD_OPTION",
  JOIN_HOUSEHOLD = "JOIN_HOUSEHOLD",
  CREATE_HOUSEHOLD = "CREATE_HOUSEHOLD",
  PAIR_DEVICE = "PAIR_DEVICE",
}
